insert into City (city_id, city_name, city_country) values (1, 'Verkhovyna', 'Ukraine');
insert into City (city_id, city_name, city_country) values (2, 'Qingchuan', 'China');
insert into City (city_id, city_name, city_country) values (3, 'Brejo Santo', 'Brazil');
insert into City (city_id, city_name, city_country) values (4, 'Batan', 'Philippines');
insert into City (city_id, city_name, city_country) values (5, 'Chengxiang', 'China');
insert into City (city_id, city_name, city_country) values (6, 'Puerto Plata', 'Dominican Republic');
insert into City (city_id, city_name, city_country) values (7, 'Krebet', 'Indonesia');
insert into City (city_id, city_name, city_country) values (8, 'Hoboksar', 'China');
insert into City (city_id, city_name, city_country) values (9, 'Rejoagung', 'Indonesia');
insert into City (city_id, city_name, city_country) values (10, 'Tsukumiura', 'Japan');
insert into City (city_id, city_name, city_country) values (11, 'Ribeira Seca', 'Portugal');
insert into City (city_id, city_name, city_country) values (12, 'Oganlima', 'Indonesia');
insert into City (city_id, city_name, city_country) values (13, 'Danan', 'China');
insert into City (city_id, city_name, city_country) values (14, 'Georgīevka', 'Kazakhstan');
insert into City (city_id, city_name, city_country) values (15, 'La Dorada', 'Colombia');
insert into City (city_id, city_name, city_country) values (16, 'Runović', 'Croatia');
insert into City (city_id, city_name, city_country) values (17, 'Molochnoye', 'Russia');
insert into City (city_id, city_name, city_country) values (18, 'Suqu', 'China');
insert into City (city_id, city_name, city_country) values (19, 'Valence', 'France');
insert into City (city_id, city_name, city_country) values (20, 'Karabash', 'Russia');
insert into City (city_id, city_name, city_country) values (21, 'Miaoli', 'Taiwan');
insert into City (city_id, city_name, city_country) values (22, 'Sokółka', 'Poland');
insert into City (city_id, city_name, city_country) values (23, 'Hînceşti', 'Moldova');
insert into City (city_id, city_name, city_country) values (24, 'Fenais da Ajuda', 'Portugal');
insert into City (city_id, city_name, city_country) values (25, 'Lancar', 'Indonesia');
insert into City (city_id, city_name, city_country) values (26, 'Rakaia', 'New Zealand');
insert into City (city_id, city_name, city_country) values (27, 'Frei', 'Norway');
insert into City (city_id, city_name, city_country) values (28, 'Gyangkar', 'China');
insert into City (city_id, city_name, city_country) values (29, 'Kalnibolotskaya', 'Russia');
insert into City (city_id, city_name, city_country) values (30, 'Zheleznovodsk', 'Russia');
insert into City (city_id, city_name, city_country) values (31, 'Chishui', 'China');
insert into City (city_id, city_name, city_country) values (32, 'Osveya', 'Belarus');
insert into City (city_id, city_name, city_country) values (33, 'Paitan', 'Philippines');
insert into City (city_id, city_name, city_country) values (34, 'Leluo', 'China');
insert into City (city_id, city_name, city_country) values (35, 'Kangān', 'Iran');
insert into City (city_id, city_name, city_country) values (36, 'Shanxiahu', 'China');
insert into City (city_id, city_name, city_country) values (37, 'Vallenar', 'Chile');
insert into City (city_id, city_name, city_country) values (38, 'Manutapen', 'Indonesia');
insert into City (city_id, city_name, city_country) values (39, 'Rancageneng Satu', 'Indonesia');
insert into City (city_id, city_name, city_country) values (40, 'Bayt Maqdūm', 'Palestinian Territory');
insert into City (city_id, city_name, city_country) values (41, 'Compostela', 'Philippines');
insert into City (city_id, city_name, city_country) values (42, 'Liuhu', 'China');
insert into City (city_id, city_name, city_country) values (43, 'Kizilyurt', 'Russia');
insert into City (city_id, city_name, city_country) values (44, 'Sabang', 'Philippines');
insert into City (city_id, city_name, city_country) values (45, 'Borgustanskaya', 'Russia');
insert into City (city_id, city_name, city_country) values (46, 'Hayang', 'South Korea');
insert into City (city_id, city_name, city_country) values (47, 'Dasol', 'Philippines');
insert into City (city_id, city_name, city_country) values (48, 'Kongjiang', 'China');
insert into City (city_id, city_name, city_country) values (49, 'Wydminy', 'Poland');
insert into City (city_id, city_name, city_country) values (50, 'Calaoagan', 'Philippines');
