insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (1, 'massa volutpat', 27, '15348 Fordem Alley', 42389, 'fstuehmeier0@webnode.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (2, 'vitae ipsum aliquam', 37, '7417 Atwood Plaza', 95318, 'mpickup1@vimeo.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (3, 'curae', 3, '8 Mccormick Plaza', 32137, 'ebrookes2@1688.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (4, 'eget eleifend', 40, '82172 Erie Pass', 66454, 'qknights3@slideshare.net');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (5, 'at diam', 30, '885 Hoard Avenue', 77313, 'maiers4@flavors.me');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (6, 'duis bibendum', 15, '80454 Monument Street', 76552, 'rblackaller5@rakuten.co.jp');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (7, 'duis ac', 6, '7 Union Center', 67940, 'wprevett6@list-manage.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (8, 'accumsan', 20, '4 Sutteridge Road', 74773, 'eneilus7@auda.org.au');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (9, 'ut ultrices vel', 8, '951 Quincy Terrace', 48675, 'chusselbee8@latimes.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (10, 'integer aliquet', 48, '7700 Esker Court', 68691, 'vholtaway9@godaddy.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (11, 'rhoncus aliquam', 35, '48675 Clyde Gallagher Drive', 87338, 'randreuccia@gizmodo.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (12, 'pede libero quis', 4, '3 Heffernan Terrace', 31226, 'kvanderweedenburgb@google.cn');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (13, 'et ultrices posuere', 34, '684 Crowley Place', 52587, 'bmorecombc@ox.ac.uk');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (14, 'suscipit', 33, '9 School Hill', 47296, 'rsimonnetd@behance.net');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (15, 'sem mauris laoreet', 46, '0 John Wall Crossing', 4645, 'egutersone@google.pl');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (16, 'nec molestie sed', 46, '1504 Maryland Street', 99865, 'lmcgilbonf@artisteer.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (17, 'justo eu', 18, '51682 Morrow Way', 17870, 'amarmyong@npr.org');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (18, 'cursus id', 14, '752 Maryland Alley', 83173, 'gturfsh@51.la');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (19, 'proin leo odio', 36, '24 Red Cloud Junction', 46745, 'ewendoveri@weather.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (20, 'feugiat non pretium', 13, '58 Express Crossing', 68915, 'tackredj@bloomberg.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (21, 'eu felis fusce', 14, '076 Packers Terrace', 92009, 'ksneydk@narod.ru');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (22, 'arcu libero', 8, '55880 Oakridge Lane', 99206, 'fsibbertl@samsung.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (23, 'ultricies eu nibh', 20, '1 Melby Park', 9401, 'zskillingm@exblog.jp');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (24, 'vestibulum', 38, '0309 Eastlawn Pass', 40218, 'zsaffenn@uiuc.edu');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (25, 'enim', 46, '8 Dottie Lane', 35525, 'gmerigoto@youtu.be');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (26, 'sociis natoque', 46, '6964 Ridgeview Parkway', 28576, 'dbridgettp@jiathis.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (27, 'amet eros', 23, '8974 Memorial Street', 92587, 'lbuglerq@yahoo.co.jp');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (28, 'at diam', 11, '82695 Ilene Circle', 6938, 'clogsdaler@xrea.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (29, 'curabitur', 41, '706 Steensland Trail', 21928, 'tmacmeekings@parallels.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (30, 'vulputate vitae nisl', 11, '2 Jana Crossing', 55173, 'rsanperet@woothemes.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (31, 'aliquam non', 19, '68 Onsgard Parkway', 57239, 'mspirrittu@nymag.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (32, 'magna at nunc', 7, '9 Montana Hill', 99374, 'tcicchettov@soundcloud.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (33, 'in', 45, '58 Michigan Court', 70612, 'mgierekw@istockphoto.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (34, 'ut dolor', 27, '7903 Bayside Terrace', 21889, 'bmcclunex@aol.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (35, 'at turpis a', 49, '6723 Morning Alley', 93449, 'tvurleyy@fastcompany.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (36, 'morbi', 40, '8101 Dwight Center', 73879, 'skildahlz@telegraph.co.uk');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (37, 'felis sed interdum', 15, '15 Hollow Ridge Parkway', 32830, 'swaterhowse10@dyndns.org');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (38, 'sapien urna', 27, '2 Rowland Court', 16424, 'ekivits11@foxnews.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (39, 'duis aliquam convallis', 9, '74617 Maple Wood Alley', 71433, 'vtithacott12@ucla.edu');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (40, 'ut odio', 21, '00223 Cascade Avenue', 10911, 'eyeowell13@cisco.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (41, 'ultrices', 1, '03944 Ridgeview Plaza', 57779, 'dhansard14@craigslist.org');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (42, 'diam id', 12, '3 Southridge Trail', 12017, 'cogrogane15@vk.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (43, 'enim lorem ipsum', 8, '08389 Butterfield Parkway', 16656, 'ediwell16@ca.gov');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (44, 'quis', 38, '5 Pearson Alley', 85862, 'tgarrity17@indiatimes.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (45, 'ante ipsum', 5, '60 Surrey Center', 1283, 'ndodds18@geocities.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (46, 'convallis', 2, '7197 Spenser Street', 8068, 'cflintoffe19@booking.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (47, 'purus aliquet at', 26, '6 Trailsway Court', 2656, 'pbaston1a@tripadvisor.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (48, 'sed nisl nunc', 12, '5 Westend Crossing', 38982, 'gtarquinio1b@ucsd.edu');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (49, 'rutrum', 19, '495 Debs Parkway', 71236, 'mchastang1c@photobucket.com');
insert into Venue (venue_id, venue_name, city_id, venue_address, venue_capacity, venue_email) values (50, 'viverra eget congue', 4, '41550 Summit Way', 91847, 'gteas1d@infoseek.co.jp');
